// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/location": {
            "get": {
                "description": "Looks up a city-level place name via Nominatim. Coordinates are rounded to 2 decimals and responses are cached for 24 hours (see the X-Cache header).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Reverse-geocode coordinates",
                "parameters": [
                    {
                        "type": "number",
                        "example": 55.68,
                        "description": "Latitude (-90 to 90)",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "example": 12.57,
                        "description": "Longitude (-180 to 180)",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.LocationResponse"
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "HIT or MISS"
                            }
                        }
                    },
                    "400": {
                        "description": "valid lat and lon are required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Location not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to encode location",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Failed to look up location",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/login": {
            "post": {
                "description": "Verifies the password (bcrypt, with transparent upgrade of legacy MD5 hashes) and redirects to / on success. If username or password is missing entirely, the response is 422 with an empty JSON object. No session or token is issued.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Log in",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "303": {
                        "description": "Redirect to /",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid username or password",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Missing fields",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database or hashing error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/logout": {
            "get": {
                "description": "Returns a confirmation message. There is no server-side session to end.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Log out",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.MessageResponse"
                        }
                    }
                }
            }
        },
        "/api/register": {
            "post": {
                "description": "Validates the form, rejects duplicate usernames/emails, stores a bcrypt hash and redirects to /login. If any of the four fields is missing entirely, the response is 422 with an empty JSON object.",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Register a user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Email address (must contain @)",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password repeated (must match)",
                        "name": "password2",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "303": {
                        "description": "Redirect to /login",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Username or email already exists",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Validation error",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database or hashing error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/search": {
            "get": {
                "description": "Returns pages in the given language whose content contains the query string.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search pages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search query",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "en",
                        "description": "Language code",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SearchResponse"
                        }
                    },
                    "422": {
                        "description": "q is missing",
                        "schema": {
                            "$ref": "#/definitions/main.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/weather": {
            "get": {
                "description": "Proxies Open-Meteo for the given coordinates. Coordinates are rounded to 2 decimals and responses are cached for 15 minutes (see the X-Cache header).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "weather"
                ],
                "summary": "Get weather forecast",
                "parameters": [
                    {
                        "type": "number",
                        "example": 55.68,
                        "description": "Latitude (-90 to 90)",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "example": 12.57,
                        "description": "Longitude (-180 to 180)",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.WeatherResponse"
                        },
                        "headers": {
                            "X-Cache": {
                                "type": "string",
                                "description": "HIT or MISS"
                            }
                        }
                    },
                    "400": {
                        "description": "valid lat and lon are required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "502": {
                        "description": "Failed to fetch weather",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "q is required"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 422
                }
            }
        },
        "main.LocationResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "Copenhagen, Denmark"
                }
            }
        },
        "main.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Logged out"
                },
                "statusCode": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "main.SearchResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.SearchResult"
                    }
                }
            }
        },
        "main.SearchResult": {
            "type": "object",
            "properties": {
                "Description": {
                    "type": "string"
                },
                "Title": {
                    "type": "string"
                },
                "URL": {
                    "type": "string"
                }
            }
        },
        "main.WeatherCurrent": {
            "type": "object",
            "properties": {
                "temperature_2m": {
                    "type": "number",
                    "example": 14.2
                },
                "weather_code": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "main.WeatherDaily": {
            "type": "object",
            "properties": {
                "temperature_2m_max": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "temperature_2m_min": {
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "time": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "weather_code": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "main.WeatherResponse": {
            "type": "object",
            "properties": {
                "current": {
                    "$ref": "#/definitions/main.WeatherCurrent"
                },
                "daily": {
                    "$ref": "#/definitions/main.WeatherDaily"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "WhoKnows Search API",
	Description:      "Search, user and weather endpoints for the WhoKnows search app.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
